In [2]:
#Index retrieval
import numpy as np
arr=np.array([1,2,3,4,5,4,6,4])
print(arr)
x=np.where(arr==4)
print(x)

[1 2 3 4 5 4 6 4]
(array([3, 5, 7]),)


In [3]:
#Indexes where the values are even
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7]),)


In [5]:
#Sorting the array
arr=np.array([3,2,1,0])
print("\n Original array:",arr)
print("\n Sorted array:",np.sort(arr))
arr=np.array([[3,2,4],[5,0,1]])
print("\n Original array:",arr)
print("\n Sorted array:",np.sort(arr))


 Original array: [3 2 1 0]

 Sorted array: [0 1 2 3]

 Original array: [[3 2 4]
 [5 0 1]]

 Sorted array: [[2 3 4]
 [0 1 5]]


In [7]:
#Filtering of an array
import numpy as np
sorted_array=np.array([1,3,5,7])
values=[2,4,6]
insert_indices=np.searchsorted(sorted_array,values)
print(sorted_array)
print(values)
print(insert_indices)

[1 3 5 7]
[2, 4, 6]
[1 2 3]
